
name: Documentation Generation
 
on:
  # Workflow is triggered on a pull_request to the main branch
  # When there is a push to master (achieved only by a successful merge)
  push: 
    branches:
      - 84-bug-fix-cicd
    
# Workflow of testing the code
jobs:
  document_generation:
   
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate document
        run: |
          yarn
          yarn docmd
      
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}