# Basic Cyress E2E for maintaining pull-requests and pushes.
name: Cypress E2E Test Suite
 
on:
  # Workflow is triggered on a pull request and a push
  [pull_request, push]
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run start-server
          config-file: config/cypress.config.js
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          