name: Minification and Deployment

on:
  push:
      branches:
        - 84-bug-fix-cicd

jobs:

  minify:
    name: generating minified html/js/css
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repoistory
    - uses: actions/checkout@v2

    - name: Compress HTML, CSS and JS files in source directory
      uses: nizarmah/auto-minify@v2.1
      
    - name: Commit Minified Files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: deployment
        