name: Minification and Deployment

on:
  push:
      branches:
        - 84-bug-fix-cicd

jobs:

  minify:
    name: generating minified html/js/css
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compress HTML, CSS and JS files.
      uses: nizarmah/auto-minify@master
      with:
        directory: 'source'
        overwrite: true

    - name: Commit Minified Files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: deployment
        