name: Minification and Deployment

on:
  push:
      branches:
        - main

jobs:

  minify:
    name: generating minified html/js/css
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compress HTML, CSS and JS files.
      uses: nizarmah/auto-minify@master
      with:
        directory: 'source'
        output: 'minified'
        overwrite: true

    - name: Set up deployment
      run: |
        mkdir deploy
        mkdir deploy/assets
        mkdir deploy/assets/audio
        mkdir deploy/assets/images
        mkdir deploy/components
        mkdir deploy/components/header-comp
        mkdir deploy/components/task-item
        mkdir deploy/components/task-list
        mkdir deploy/stats-page
        mkdir deploy/tasks-page
        mkdir deploy/timer-page
        cp minified/main.* deploy/
        cp minified/header-comp.* deploy/components/header-comp
        cp minified/task-item.* deploy/components/task-item
        cp minified/task-list.* deploy/components/task-list
        cp minified/stats.* deploy/stats-page
        cp minified/tasks.* deploy/tasks-page
        cp minified/timer.* deploy/timer-page
        cp minified/tutorial.js deploy/timer-page/
        cp source/index.html deploy/index.html
        cp source/timer-page/timer.html deploy/timer-page/
        cp source/tasks-page/tasks.html deploy/tasks-page/
        cp source/stats-page/stats.html deploy/stats-page/
        cp -a source/assets/images/. deploy/assets/images/
        cp -a source/assets/audio/. deploy/assets/audio/
        cp source/.firebaserc deploy/
        cp source/firebase.json deploy/
      
    - name: Deploy build files
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        publish_branch: deployment
        commit_message: ${{ github.event.head_commit.message }}
      
        