name: Minification and Deployment

on:
  push:
      branches:
        - 84-bug-fix-cicd

jobs:

  minify:
    name: generating minified html/js/css
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Auto Minify
      uses: nizarmah/auto-minify@master
      with:
        directory: source
        output: minified

    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: deployment
        