name: Minification and Deployment

on:
  push:
      branches:
        - 84-bug-fix-cicd

jobs:

  minify:
    name: generating minified html/js/css
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compress HTML, CSS and JS files.
      uses: nizarmah/auto-minify@master
      with:
        directory: 'source'
        output: 'minified'
        overwrite: true

    - name: Set up deployment
      run: |
        mkdir deploy
        mkdir deploy/assets
        mkdir deploy/assets/audio
        mkdir deploy/assets/images
        mkdir deploy/components
        mkdir deploy/components/header-comp
        mkdir deploy/components/task-item
        mkdir deploy/components/task-list
        mkdir deploy/stats-page
        mkdir deploy/tasks-page
        mkdir deploy/timer-page
        mv minified/main.* deploy/
        mv minified/tutorial.js deploy/
        mv minified/header-comp.* deploy/components/header-comp
        mv minified/task-item.* deploy/components/task-item
        mv minified/task-list.* deploy/components/task-list
        mv minified/stats.* deploy/stats-page
        mv minified/tasks.* deploy/tasks-page
        mv minified/timer.* deploy/timer-page
        cp source/index.html deploy/index.html
        cp source/timer-page/timer.html deploy/timer-page/timer.html
        cp source/stats-page/stats.html deploy/stats-page/stats.html
        cp -a source/assets/images/. deploy/assets/images/
        cp -a source/assets/audio/. deploy/assets/audio/
      
    - name: Commit Minified Files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        repository: ./deploy
        branch: deployment
      
        